os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - 'lts/*'
  - '8'
  - '10'
  - '12'
cache: yarn
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xsel; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sh -e /etc/init.d/xvfb start; sleep 3; fi'
  - npm install --global nyc
script:
  - yarn build
  - yarn test-coverage
after_script:
  - npm install --global codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov | codecov
