# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'win1803'
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'Yarn install'

- script: |
    yarn build
  displayName: 'build'

- script: |
    yarn test-coverage
  displayName: 'test-coverage'

- script: |
   npm install --global codecov coveralls
   nyc report --reporter=text-lcov | coveralls
   nyc report --reporter=text-lcov | codecov
  displayName: 'report-coverage'
