name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        NODE:
          - 12.x
          - 10.x
        PLATFORM:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}

    runs-on: ${{ matrix.PLATFORM }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.NODE }}

      - name: Install
        run: |
          npm install --global nyc
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test-coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
