name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        PLATFORM:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        NODE:
          - 12.x
          - 10.x
      fail-fast: false

    name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}

    runs-on: ${{ matrix.PLATFORM }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.NODE }}

      - run: npm install --global nyc
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sh -e /etc/init.d/xvfb start
          sleep 3
        env:
          DISPLAY: :99.0

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test-coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
