name: Test

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

  test:
    strategy:
      matrix:
        PLATFORM:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        NODE:
          - 12.x
          # - 10.x
      fail-fast: false

    name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}

    runs-on: ${{ matrix.PLATFORM }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.NODE }}

      - run: npm install --global nyc

      - name: Linux Setup
        if: matrix.PLATFORM == 'ubuntu-latest'
        run: |
          chmod +x ./scripts/xvfb.init
          ./scripts/xvfb.init start

      - name: Windows Setup
        if: matrix.PLATFORM == 'windows-latest'
        run: echo %YARN_GPG%
        env:
          YARN_GPG: no

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: |
          echo $DISPLAY
          yarn test-coverage
        env:
          DISPLAY: :99.0

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
